### PR TITLE
fix: transfer method polkadot js update

### LINKED ISSUE #206: The wallet is not reflecting the right balance on the polkadot network
Log: 

sendSnapMethod 
{method: 'getBalance'}
method
: 
"getBalance"

RPC Error: The snap "npm:@chainsafe/polkadot-snap" has been terminated during execution. {code: -32603, message: 'The snap "npm:@chainsafe/polkadot-snap" has been terminated during execution.'.

---
MetaMask - RPC Error: The request timed out. 

{
    "code": -32603,
    "message": "The request timed out.",
    "data": {
        "originalError": {}
    }
}

### PR DESCRIPTION
**Pull request by Lykhoyda**
Transfer method got deprecated, updated with transferAllowDeath
https://github.com/paritytech/substrate/pull/12951

Fix #206

### CODE REVIEW

**Comment by Lykhoyda** [comment]
P.S. I removed "yarn": cache due to errors during ci 
https://chainsafeio.slack.com/archives/C02M9NP8J79/p1700566727057229?thread_ts=1700566666.613659&cid=C02M9NP8J79

File: packages/snap/src/rpc/generateTransactionPayload.ts [hunk 1]
```diff
@@ -20,8 +20,12 @@ export async function generateTransactionPayload(
     }),
     nonce
   };
+
   // define transaction method
-  const transaction: SubmittableExtrinsic<'promise'> = api.tx.balances.transfer(to, amount);
+  const transaction: SubmittableExtrinsic<'promise'> = api.tx.balances.transferAllowDeath(
```
Comment (mpetrunic) [inline packages/snap/src/rpc/generateTransactionPayload.ts:25]: Why not use transferKeepAlive?

Comment (Tbaut) [reply packages/snap/src/rpc/generateTransactionPayload.ts:25]: agreed, it should be `transferKeepAlive` which is more safe for users.

File: packages/snap/src/rpc/send.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ export async function send(
 
   const amount = extrinsic.args[1].toJSON();
   const paymentInfo = await api.tx.balances
-    .transfer(destination, String(amount))
+    .transferAllowDeath(destination, String(amount))
```
Comment (Tbaut) [inline packages/snap/src/rpc/send.ts:19]: same here

File: packages/snap/src/rpc/generateTransactionPayload.ts (hunk 1 above)
Comment (Lykhoyda) [reply packages/snap/src/rpc/generateTransactionPayload.ts:25]: yeah, probably indeed transferKeepAlive is safer

**Review by Tbaut — APPROVED** [review]

**Review by BeroBurny — APPROVED** [review]
